
name: Publish Package
on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish TypeDI to NPM
    runs-on: ubuntu-latest
    steps:
      # The rest of this scripts runs the various tasks.
      # - run: pnpm install --ignore-scripts
      - run: pnpm install
      - run: pnpm run prettier:check
      - run: pnpm run lint:check
      - run: pnpm run test:ci
      - run: pnpm run build:esm5
      - run: pnpm run build:cjs
      - run: pnpm run build:umd
      - run: pnpm run build:types
      - run: cp LICENSE build/LICENSE
      - run: cp README.md build/README.md
      # Copy the package.json to the newly-created build folder, without devDependencies and scripts present.
      - run: jq 'del(.devDependencies) | del(.scripts)' package.json > build/package.json
      # Finally, publish the build to NPM.
      # - run: pnpm publish ./build
        # env:
        #   # Get this via NPM's webpage.
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
