
name: Publish Package
on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish TypeDI to NPM
    runs-on: ubuntu-latest
    uses: freshgum-bubbles/typedi/.github/workflows/prepare-package-manager-workflow.yml@develop
    steps:
      # The rest of this scripts runs the various tasks.
      # - run: pnpm ci --ignore-scripts
      - run: pnpm ci
      - run: pnpm run prettier:check
      - run: pnpm run lint:check
      - run: pnpm run test:ci
      - run: pnpm run build:es2015
      - run: pnpm run build:esm5
      - run: pnpm run build:cjs
      - run: pnpm run build:umd
      - run: pnpm run build:types
      - run: cp LICENSE build/LICENSE
      - run: cp README.md build/README.md
      # Copy the package.json to the newly-created build folder, without devDependencies and scripts present.
      - run: jq 'del(.devDependencies) | del(.scripts)' package.json > build/package.json
      # Finally, publish the build to NPM.
      - run: pnpm publish ./build
        env:
          # Get this via NPM's webpage.
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}