name: Continuous Integration
on: [push, pull_request]
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: ./.github/workflows/prepare-package-manager-workflow.yml
      - run: pnpm run prettier:check
      - run: pnpm run lint:check
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: ./.github/workflows/prepare-package-manager-workflow.yml
      - run: pnpm run test:ci
      - run: pnpm install codecov -g
      - run: codecov -f ./coverage/clover.xml -t ${{ secrets.CODECOV_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 'lts/*'
      - uses: ./.github/workflows/prepare-package-manager-workflow.yml
      - run: pnpm run build:es2015
      - run: pnpm run build:esm5
      - run: pnpm run build:cjs
      - run: pnpm run build:umd
      - run: pnpm run build:types
